name: Update README

on:
  workflow_dispatch:      # option to run manually
  push:                   # run on each push
  schedule:
    - cron: "0 0 * * */1" # runs at 0:00 UTC each day

jobs:
  markscribe:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.0

      - name: Use Node.js 14
        uses: actions/setup-node@v14

      - name: Install dependencies
        run: npm install

      - name: Run readme-scribe
        run: npx readme-scribe

      - name: Commit changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "readme-scribe 🤖"
          git add README.md
          git commit -m "Update generated README"

  update-badges:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    needs: markscribe

    steps:
      - name: Badges - Readme
        uses: pemtajo/badge-readme@2.4.0
        with:
          CREDLY_SORT: POPULAR