name: Update README

on:
  push:
  schedule:
    - cron: "0 0 * * */1" # runs at 0:00 UTC each day

jobs:
  markscribe:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.3.0

      - uses: D0rDa4aN919/readme-scribe@v0.1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        with:
          template: "templates/README.md.tpl"
          writeTo: "README.md"

      - uses: stefanzweifel/git-auto-commit-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: Update generated README
          branch: main
          commit_user_name: readme-scribe 🤖
          commit_user_email: actions@github.com
          commit_author: readme-scribe 🤖 <actions@github.com>
          update-badges:
- name: Update RSS Feed
  uses: actions/setup-node@v3
  with:
    node-version: '14'
- name: Fetch RSS Feed
  run: npm install --global rss-parser && node fetch-rss.js
