name: Update README

on:
  push:
  schedule:
    - cron: "0 0 * * */1"

jobs:
  markscribe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.0
      
      - uses: jetzlstorfer/readme-scribe@master
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
        with:
          template: "templates/README.md.tpl"
          writeTo: "README.md"

      - uses: stefanzweifel/git-auto-commit-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
        with:
          commit_message: Update generated README
          branch: main
          commit_user_name: readme-scribe 🤖
          commit_user_email: actions@github.com
          commit_author: readme-scribe 🤖 <actions@github.com>

  update-badges:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    needs: markscribe
    steps:
      - name: Badges - Readme
        uses: pemtajo/badge-readme@2.4.0
        with:
          CREDLY_SORT: POPULAR
